# -*- coding: utf-8 -*-
"""
Created on Wed Nov 13 17:33:49 2024

Author: Lucía Lopez
Florencia D. Choque
Giovanni Ferrari
Description:
This script processes experimental pMINFLUX data using fitted point spread functions (PSFs) and TCSPC data.
At this stage, the MINFLUX excitation pattern has already been aligned, and the distances between the minima of the pattern 
have been confirmed to be good enough after a fitting process. 
This alignment and quality check are performed using `analise_EBP`, which operates on the raw PSFs generated by the MINFLUX setup.

Recommendations:
- Verify the τ parameter values, as they correspond to the peaks in the relative time histogram. 
Any hardware changes, such as swapping cables, may alter these values, potentially introducing errors. 
Future versions should automate this calibration to enhance robustness.

Details:
- An offset is applied to the relative time histogram peaks to match the acquisition order of the setup's PSFs.
- The `lifetime_win_i` and `lifetime_win_f` parameters specify the time window used for photon counting.

Note:
This code still requires adaptation for tracking experiments using Swabian hardware. But so far this is our working version.

"""

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from natsort import natsorted

from tracking_analysis.config.configvar import (
    DIR_BASE,
    PSF_DIR_BASE,
    DATA_DIR_BASE,
    IRF_DIR_BASE,
    LOCS_FILE_SUFFIX_NOLT,
    LOCS_FILE_SUFFIX_LT,
    PULSES_POS_NS,
    TCSPC_SUFFIX,
    TCSPC_EXT,
    DRIFT_SUFFIX,
    DRIFT_EXT,
    EBP_DIR_SUFFIX,
    PSF_FIT_DIR_NAME,
    HMM_WLT_SUFFIX
)
from tracking_analysis.ebp import EBP
from tracking_analysis.tcspcdata import TCSPCData
from tracking_analysis.minfluxanalysis import MINFLUXAnalysis
from tracking_analysis.postprocessing import DataPostProcessor
from tracking_analysis.origamianalysis import SMOrigamiAnalysis, ClockOrigamiAnalysis
from tracking_analysis.endoivanalysis import EndoIVAnalysis

plt.close('all')

date = '20260129'

meas_name = 'g1_mol3'
channel_name = 'red'
meas_number = 2

ebp_number = 2
color = 'r'

if meas_number==0:
    filename_base = meas_name + '_' + channel_name + '_' + date
else:
    filename_base = meas_name + '_' + channel_name + '_' + str(meas_number) + '_' + date
    
# TCSPC data file
tcspc_filename = filename_base + '_' + TCSPC_SUFFIX + TCSPC_EXT

# Drift data for a posteriori correction (not always used!)
drift_data_filename_base = filename_base + '_' + DRIFT_SUFFIX

# Data for background estimation when there's no bleaching (not always used!)
bckg_filename = 'bckg_sixsites_red_20251217_arrays.ptu'

# Data for background from dark counts estimation when power is variable during measurement (not always used!)
bckg_dark_cnts_filename = 'bckg_dark_cnts__20250224-162247_.npy'

# IRF file (not always used!)
irf_filename = 'IRF_MINFLUX_red_20260120_60kcps_1.ptu'

psf_dir = PSF_DIR_BASE / Path(date + '_' + EBP_DIR_SUFFIX) / Path(str(ebp_number)) / Path(color) / PSF_FIT_DIR_NAME
data_dir = DATA_DIR_BASE / date
irf_dir = IRF_DIR_BASE / channel_name
tcspc_file = data_dir / tcspc_filename
bckg_file = data_dir / bckg_filename
irf_file = irf_dir / irf_filename
bckg_file_dark_cnts_file = DIR_BASE / bckg_dark_cnts_filename
timetrace_bin_width_s = 0.1
target_n_ph = 1000

drift_filepath_list = []
for drift_filepath in natsorted(data_dir.iterdir()):
    if drift_filepath.is_file():
        if drift_data_filename_base in drift_filepath.name:
            drift_filepath_list.append(drift_filepath)

if __name__ == "__main__":
    # Open fitted experimental PSFs
    ebp = EBP(psf_dir)
    # here it is decided whether to use lifetime fitting or not
    use_lifetime_fit_choice = input("Do you want to perform lifetime fit analysis? (y/n)")
    if use_lifetime_fit_choice == 'y':
        do_lifetime_fit = True
        locs_file_suff = LOCS_FILE_SUFFIX_LT
    else:
        do_lifetime_fit = False
        locs_file_suff = LOCS_FILE_SUFFIX_NOLT
    # look for pre-existing result files
    locs_filepath_list = []
    for filepath in natsorted(data_dir.iterdir()):
        if filepath.is_file():
            if (tcspc_filename.split('.')[0] in filepath.name) and (locs_file_suff in filepath.name):
                locs_filepath_list.append(filepath)
    if locs_filepath_list:
        print("Result files found:")
        for filenumber, filepath in enumerate(locs_filepath_list):
            print(f"{filenumber}. {filepath.name}")
        use_existing_result_file_choice = input("Do you want to use an existing result file? (y/n) ")
        if use_existing_result_file_choice == 'y':
            result_filenumber_chosen = int(input("Insert number of the result file to be used: "))
    if (not locs_filepath_list) or (use_existing_result_file_choice == 'n'):
        if not locs_filepath_list:
            print("No previous result file found...")
        print("Executing full analysis.")
        # execute full analysis if no previous result file is found
        tcspc_data = TCSPCData(tcspc_file, bckg_file, bckg_file_dark_cnts_file, timetrace_bin_width_s, PULSES_POS_NS)
        minflux_analysis = MINFLUXAnalysis(ebp, tcspc_data, irf_file, target_n_ph, do_lifetime_fit)
        locs_filepath_list.append(minflux_analysis.locs_results_filepath)
        result_filenumber_chosen = -1
    locs_dens_hist_bin_size = 1
    #use_drift_data_choice_input = input("Do you want to use drift data for a posteriori correction? (y/n) ")
    use_drift_data_choice_input = 'n'
    if use_drift_data_choice_input == 'y':
        use_drift_data_choice = True
    else:
        use_drift_data_choice = False
    locs_filepath = locs_filepath_list[result_filenumber_chosen]
    if HMM_WLT_SUFFIX not in locs_filepath.name:
        postproc = DataPostProcessor(locs_filepath, drift_filepath_list, ebp, locs_dens_hist_bin_size, use_drift_data_choice, do_lifetime_fit)
        hmm_filt_done = False
    else:
        postproc = None
        hmm_filt_done = True
    print("""Do you want to perform additional analysis? Press:
1 for single-molecule/point-emitter analysis
2 for 2 sites clock analysis
3 for Endo IV bending analysis
any other key for no additional analsis""")
    analysis_choice = input()
    match analysis_choice:
        case '1':
            sm_analysis = SMOrigamiAnalysis(postproc, locs_filepath_list[result_filenumber_chosen], data_dir)
        case '2':
            clock_analysis = ClockOrigamiAnalysis(postproc, locs_filepath_list[result_filenumber_chosen], data_dir)
        case '3':
            endoiv_analysis = EndoIVAnalysis(postproc, locs_filepath_list[result_filenumber_chosen], data_dir, hmm_filt_done)
        



