# -*- coding: utf-8 -*-
"""
Created on Wed Nov 13 17:33:49 2024

Author: Lucía Lopez
Florencia D. Choque
Giovanni Ferrari
Description:
This script processes experimental pMINFLUX data using fitted point spread functions (PSFs) and TCSPC data.
At this stage, the MINFLUX excitation pattern has already been aligned, and the distances between the minima of the pattern 
have been confirmed to be good enough after a fitting process. 
This alignment and quality check are performed using `analise_EBP`, which operates on the raw PSFs generated by the MINFLUX setup.

Recommendations:
- Verify the τ parameter values, as they correspond to the peaks in the relative time histogram. 
Any hardware changes, such as swapping cables, may alter these values, potentially introducing errors. 
Future versions should automate this calibration to enhance robustness.

Details:
- An offset is applied to the relative time histogram peaks to match the acquisition order of the setup's PSFs.
- The `lifetime_win_i` and `lifetime_win_f` parameters specify the time window used for photon counting.

Note:
This code still requires adaptation for tracking experiments using Swabian hardware. But so far this is our working version.

"""

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
from natsort import natsorted

from configvar import (
    DIR_BASE,
    PSF_DIR_BASE,
    DATA_DIR_BASE,
    LOCS_FILE_SUFFIX,
    PULSES_POS_NS,
    TCSPC_SUFFIX,
    TCSPC_EXT,
    DRIFT_SUFFIX,
    DRIFT_EXT,
    EBP_DIR_SUFFIX,
    PSF_FIT_DIR_NAME
)
from ebp import EBP
from tcspcdata import TCSPCData
from minfluxanalysis import MINFLUXAnalysis
from postprocessing import DataPostProcessor
from origamianalysis import SMOrigamiAnalysis, ClockOrigamiAnalysis


plt.close('all')

date = '20251217'

meas_name = 'nc_sixsites_atto643'
channel_name = 'red'
meas_number = 5

ebp_number = 2
ebp_color = 'r'

if meas_number==0:
    filename_base = meas_name + '_' + channel_name + '_' + date
else:
    filename_base = meas_name + '_' + channel_name + '_' + str(meas_number) + '_' + date
    
# TCSPC data file
tcspc_filename = filename_base + '_' + TCSPC_SUFFIX + TCSPC_EXT

# Drift data for a posteriori correction (not always used!)
drift_data_filename_base = filename_base + '_' + DRIFT_SUFFIX

# Data for background estimation when there's no bleaching (not always used!)
bckg_filename = 'bckg_sixsites_red_20251217_arrays.ptu'

# Data for background from dark counts estimation when power is variable during measurement (not always used!)
bckg_dark_cnts_filename = 'bckg_dark_cnts__20250224-162247_.npy'

psf_dir = PSF_DIR_BASE / Path(date + '_' + EBP_DIR_SUFFIX) / Path(str(ebp_number)) / Path(ebp_color) / PSF_FIT_DIR_NAME
data_dir = DATA_DIR_BASE / date
tcspc_file = data_dir / tcspc_filename
bckg_file = data_dir / bckg_filename
bckg_file_dark_cnts_file = DIR_BASE / bckg_dark_cnts_filename
timetrace_bin_width_s = 0.1
target_n_ph = 1000

drift_filepath_list = []
for drift_filepath in natsorted(data_dir.iterdir()):
    if drift_filepath.is_file():
        if drift_data_filename_base in drift_filepath.name:
            drift_filepath_list.append(drift_filepath)

if __name__ == "__main__":
    # Open fitted experimental PSFs
    ebp = EBP(psf_dir)
    # look for pre-existing result files
    locs_filepath_list = []
    for filepath in natsorted(data_dir.iterdir()):
        if filepath.is_file():
            if (tcspc_filename.split('.')[0] in filepath.name) and (LOCS_FILE_SUFFIX in filepath.name):
                locs_filepath_list.append(filepath)
    if locs_filepath_list:
        print("Result files found:")
        for filenumber, filepath in enumerate(locs_filepath_list):
            print(f"{filenumber}. {filepath.name}")
        use_existing_result_file_choice = input("Do you want to use an existing result file? (y/n) ")
        if use_existing_result_file_choice == 'y':
            result_filenumber_chosen = int(input("Insert number of the result file to be used: "))
    if (not locs_filepath_list) or (use_existing_result_file_choice == 'n'):
        if not locs_filepath_list:
            print("No previous result file found...")
        print("Executing full analysis.")
        # execute full analysis if no previous result file is found
        tcspc_data = TCSPCData(tcspc_file, bckg_file, bckg_file_dark_cnts_file, timetrace_bin_width_s, PULSES_POS_NS)
        minflux_analysis = MINFLUXAnalysis(ebp, tcspc_data, target_n_ph)
        locs_filepath_list.append(minflux_analysis.locs_results_filepath)
        result_filenumber_chosen = -1
    locs_dens_hist_bin_size = 1
    use_drift_data_choice_input = input("Do you want to use drift data for a posteriori correction? (y/n) ")
    if use_drift_data_choice_input == 'y':
        use_drift_data_choice = True
    else:
        use_drift_data_choice = False
    postproc = DataPostProcessor(locs_filepath_list[result_filenumber_chosen], drift_filepath_list, ebp, locs_dens_hist_bin_size, use_drift_data_choice)
    sm_analysis_choice = input("Do you want to perform the analysis for the SM origami? (y/n) ")
    if sm_analysis_choice == 'y':
        sm_analysis = SMOrigamiAnalysis(postproc, locs_filepath_list[result_filenumber_chosen], data_dir)
    else:
        clock_analysis_choice = input("Do you want to perform the analysis for the clock origami? (y/n) ")
        if clock_analysis_choice == 'y':
            clock_analysis = ClockOrigamiAnalysis(postproc, locs_filepath_list[result_filenumber_chosen], data_dir)

